var searchData=
[
  ['a_20—_20reach_0',['Group A — Reach',['../index.html#autotoc_md46',1,'']]],
  ['a_20container_1',['Running LambLisp in a Container',['../index.html#containers',1,'']]],
  ['a_20container_2',['Flashing from a container',['../index.html#flashing-from-a-container',1,'']]],
  ['a_20coverage_20plan_3',['4.2 Requesting a Coverage Plan',['../index.html#fwd-jetson-plan',1,'']]],
  ['a_20guard_20that_20means_20has_20a_20socket_20must_20now_20say_20so_4',['platform. A guard that means &quot;has a socket&quot; must now SAY so.',['../ll__platform__generic_8h.html#autotoc_md206',1,'']]],
  ['a_20hierarchical_20dictionary_5',['Execution environment is a &lt;em&gt;hierarchical dictionary&lt;/em&gt;',['../index.html#arch-envdict',1,'']]],
  ['a_20jetson_20or_20raspberry_20pi_20libgpiod_6',['Real pins on a Jetson or Raspberry Pi (libgpiod)',['../index.html#llarduino-gpiod',1,'']]],
  ['a_20master_7',['2. PROFIBUS DP as a Master',['../index.html#profibus-master',1,'']]],
  ['a_20note_20on_20host_20compatibility_8',['A note on host compatibility',['../index.html#autotoc_md11',1,'']]],
  ['a_20nutshell_9',['&lt;em&gt;Lisp&lt;/em&gt; in a nutshell',['../index.html#autotoc_md17',1,'']]],
  ['a_20peripheral_10',['3.1 Opening a Peripheral',['../index.html#modbus-peripheral-open',1,'']]],
  ['a_20pin_11',['Where these run, and what actually drives a pin',['../index.html#llarduino-backends',1,'']]],
  ['a_20real_20time_20control_20system_12',['What is a real-time control system?',['../index.html#autotoc_md175',1,'']]],
  ['a_20slave_13',['3. PROFIBUS DP as a Slave',['../index.html#profibus-slave',1,'']]],
  ['a_20socket_20must_20now_20say_20so_14',['platform. A guard that means &quot;has a socket&quot; must now SAY so.',['../ll__platform__generic_8h.html#autotoc_md206',1,'']]],
  ['a_20string_20may_20contain_20nul_20and_20string_20length_20is_20the_20authority_15',['A string may contain NUL, and &lt;span class=&quot;tt&quot;&gt;string-length&lt;/span&gt; is the authority',['../index.html#autotoc_md147',1,'']]],
  ['aarch64_16',['4.1 Linux (x86_64 and aarch64)',['../index.html#modbus-linux',1,'']]],
  ['access_20point_20softap_17',['WiFi Access Point (softAP)',['../index.html#wifi-softap',1,'']]],
  ['accessors_18',['3.3 Register Accessors',['../index.html#modbus-register-accessors',1,'']]],
  ['accumulator_20floor_20map_20scm_19',['3.1 Map Accumulator (&lt;span class=&quot;tt&quot;&gt;floor-map.scm&lt;/span&gt;)',['../index.html#fwd-floor-map-scm',1,'']]],
  ['acknowledgements_20',['Acknowledgements',['../index.html#autotoc_md204',1,'']]],
  ['actually_20drives_20a_20pin_21',['Where these run, and what actually drives a pin',['../index.html#llarduino-backends',1,'']]],
  ['adaptive_20real_20time_20garbage_20collection_22',['Adaptive real-time garbage collection',['../index.html#autotoc_md23',1,'']]],
  ['addressable_20led_20strip_20neopixel_23',['WS2812 Addressable LED Strip (NeoPixel)',['../index.html#autotoc_md99',1,'']]],
  ['addressable_20leds_20ws2812_20scm_24',['Addressable LEDs (&lt;span class=&quot;tt&quot;&gt;WS2812.scm&lt;/span&gt;)',['../index.html#autotoc_md104',1,'']]],
  ['advanced_25',['WiFi Station — Advanced',['../index.html#wifi-station-adv',1,'']]],
  ['advantages_20of_20lamblisp_20in_20combination_20with_20c_20c_20on_20micro_20controllers_26',['What are the advantages of &lt;em&gt;LambLisp&lt;/em&gt; in combination with C/C++ on micro-controllers?',['../index.html#autotoc_md197',1,'']]],
  ['ai_20and_20machine_20to_20machine_27',['AI and Machine-to-Machine',['../index.html#autotoc_md48',1,'']]],
  ['ai_20orchestration_20and_20the_20robot_20stack_28',['AI Orchestration and the Robot Stack',['../index.html#llip-robot',1,'']]],
  ['air_20updates_29',['Over-the-Air Updates',['../index.html#ota',1,'']]],
  ['air_20updates_20without_20reboot_30',['Incremental over-the-air updates without reboot',['../index.html#autotoc_md24',1,'']]],
  ['algebra_31',['Array math (linear algebra)',['../index.html#ndarray',1,'']]],
  ['all_20platforms_32',['Does the same Scheme code run on all platforms?',['../index.html#autotoc_md183',1,'']]],
  ['already_20inside_33',['The documentation is already inside',['../index.html#autotoc_md9',1,'']]],
  ['already_20rooted_20for_20you_34',['What is already rooted for you',['../index.html#autotoc_md64',1,'']]],
  ['an_20embedded_20board_35',['Flash an embedded board',['../index.html#package-flash',1,'']]],
  ['an_20rtos_36',['Can I use LambLisp without an RTOS?',['../index.html#autotoc_md201',1,'']]],
  ['and_20aarch64_37',['4.1 Linux (x86_64 and aarch64)',['../index.html#modbus-linux',1,'']]],
  ['and_20arq_20llip_20serial_20scm_38',['Serial Transport and ARQ (&lt;span class=&quot;tt&quot;&gt;llip-serial.scm&lt;/span&gt;)',['../index.html#llip-serial',1,'']]],
  ['and_20ascii_20render_39',['5.2 Map Store and ASCII Render',['../index.html#fwd-cloud-mapstore',1,'']]],
  ['and_20boards_40',['Supported Platforms and Boards',['../index.html#supported-platforms',1,'']]],
  ['and_20c_20api_41',['Language Internals and C++ API',['../index.html#autotoc_md53',1,'']]],
  ['and_20collisions_42',['Hash table sizing and collisions',['../index.html#autotoc_md59',1,'']]],
  ['and_20conformance_43',['Language and Conformance',['../index.html#autotoc_md185',1,'']]],
  ['and_20development_20tools_44',['Diagnostics and Development Tools',['../index.html#autotoc_md76',1,'']]],
  ['and_20evaluation_45',['Environments and Evaluation',['../index.html#autotoc_md155',1,'']]],
  ['and_20flash_46',['Build and Flash',['../index.html#autotoc_md15',1,'']]],
  ['and_20gc_20tuning_47',['and GC Tuning',['../index.html#arch-adaptive',1,'Memory and GC Tuning'],['../index.html#gc-tuning',1,'Runtime and GC Tuning']]],
  ['and_20global_20control_48',['2.5 Diagnostics and Global Control',['../index.html#profibus-diag',1,'']]],
  ['and_20hashing_20details_49',['Hash table and hashing details',['../index.html#autotoc_md58',1,'']]],
  ['and_20list_20structures_50',['Cell Memory Model and List Structures',['../index.html#autotoc_md41',1,'']]],
  ['and_20lists_51',['Pairs and Lists',['../index.html#autotoc_md142',1,'']]],
  ['and_20machine_20to_20machine_52',['AI and Machine-to-Machine',['../index.html#autotoc_md48',1,'']]],
  ['and_20macro_53',['lambda, nlambda, and macro',['../index.html#arch-lambda',1,'']]],
  ['and_20memory_20tuning_54',['GC and memory tuning',['../index.html#autotoc_md84',1,'']]],
  ['and_20motors_20pca9685_20scm_55',['Servos and Motors (&lt;span class=&quot;tt&quot;&gt;PCA9685.scm&lt;/span&gt;)',['../index.html#autotoc_md103',1,'']]],
  ['and_20naming_56',['6. Certification and Naming',['../index.html#fieldbus-certification',1,'']]],
  ['and_20non_20symbol_20keys_57',['Objects and non-symbol keys',['../index.html#autotoc_md61',1,'']]],
  ['and_20on_20board_20display_20esp32_20s3_20eye_58',['Camera and On-Board Display (esp32-s3-eye)',['../index.html#camera',1,'']]],
  ['and_20operation_59',['Integration and Operation',['../index.html#autotoc_md196',1,'']]],
  ['and_20output_60',['Input and Output',['../index.html#autotoc_md159',1,'']]],
  ['and_20pre_20reserve_61',['Memory Tuning: Stack Size, DMA Memory, and Pre-Reserve',['../index.html#esp32-memory-tuning',1,'']]],
  ['and_20profinet_20interface_62',['LambLisp PROFIBUS and PROFINET Interface',['../index.html#fieldbus',1,'']]],
  ['and_20scheme_63',['Brief history of Lisp and Scheme',['../index.html#arch-history',1,'']]],
  ['and_20scm_20are_20not_20the_20same_20thing_64',['&lt;span class=&quot;tt&quot;&gt;data/&lt;/span&gt; and &lt;span class=&quot;tt&quot;&gt;scm/&lt;/span&gt; are not the same thing',['../index.html#data-vs-scm',1,'']]],
  ['and_20start_20the_20car_65',['6.2 Flash and Start the Car',['../index.html#fwd-run-car',1,'']]],
  ['and_20string_20length_20is_20the_20authority_66',['A string may contain NUL, and &lt;span class=&quot;tt&quot;&gt;string-length&lt;/span&gt; is the authority',['../index.html#autotoc_md147',1,'']]],
  ['and_20system_67',['Timing and system',['../index.html#autotoc_md83',1,'']]],
  ['and_20tail_20calls_68',['Tail recursion and tail-calls',['../index.html#autotoc_md28',1,'']]],
  ['and_20the_20robot_20stack_69',['AI Orchestration and the Robot Stack',['../index.html#llip-robot',1,'']]],
  ['and_20what_20actually_20drives_20a_20pin_70',['Where these run, and what actually drives a pin',['../index.html#llarduino-backends',1,'']]],
  ['and_20what_20is_20not_71',['and what is not',['../index.html#autotoc_md8',1,'What is in the image, and what is not'],['../index.html#autotoc_md6',1,'What is the same as Linux, and what is not']]],
  ['and_20why_20it_20exists_72',['The baud ceiling, and why it exists',['../index.html#profibus-baud-ceiling',1,'']]],
  ['any_20directory_73',['Running from any directory',['../index.html#autotoc_md5',1,'']]],
  ['api_74',['API',['../index.html#profinet-api',1,'5.2 The API'],['../index.html#autotoc_md53',1,'Language Internals and C++ API']]],
  ['api_20for_20new_20lisp_20primitives_75',['Open API for new &lt;em&gt;Lisp&lt;/em&gt; primitives',['../index.html#open-api',1,'']]],
  ['api_20llip_20client_20scm_76',['Client API (&lt;span class=&quot;tt&quot;&gt;llip-client.scm&lt;/span&gt;)',['../index.html#autotoc_md90',1,'']]],
  ['applications_20as_20virtual_20machines_77',['Control Applications as Virtual Machines.',['../index.html#autotoc_md37',1,'']]],
  ['arbitrary_20precision_20integers_20bignums_78',['Arbitrary-Precision Integers (Bignums)',['../index.html#bignum',1,'']]],
  ['architecture_79',['Role in the Supervisory Architecture',['../index.html#autotoc_md93',1,'']]],
  ['architecture_20internals_80',['LambLisp Architecture Internals',['../index.html#autotoc_md32',1,'']]],
  ['architecture_20notes_81',['7. Architecture Notes',['../index.html#fwd-arch-notes',1,'']]],
  ['arduino_20embedded_20i_20o_82',['Arduino / Embedded I/O',['../index.html#llarduino',1,'']]],
  ['arduino_20libraries_83',['Reuse of existing C++/Arduino libraries',['../index.html#autotoc_md22',1,'']]],
  ['are_20first_20class_20data_20types_84',['Procedures are first-class data types',['../index.html#autotoc_md29',1,'']]],
  ['are_20not_20the_20same_20thing_85',['&lt;span class=&quot;tt&quot;&gt;data/&lt;/span&gt; and &lt;span class=&quot;tt&quot;&gt;scm/&lt;/span&gt; are not the same thing',['../index.html#data-vs-scm',1,'']]],
  ['are_20the_20advantages_20of_20lamblisp_20in_20combination_20with_20c_20c_20on_20micro_20controllers_86',['What are the advantages of &lt;em&gt;LambLisp&lt;/em&gt; in combination with C/C++ on micro-controllers?',['../index.html#autotoc_md197',1,'']]],
  ['are_20wrappers_20around_20hierarchical_20dictionaries_87',['Objects are wrappers around &lt;em&gt;hierarchical dictionaries&lt;/em&gt;',['../index.html#autotoc_md34',1,'']]],
  ['around_20hierarchical_20dictionaries_88',['Objects are wrappers around &lt;em&gt;hierarchical dictionaries&lt;/em&gt;',['../index.html#autotoc_md34',1,'']]],
  ['arq_20llip_20serial_20scm_89',['Serial Transport and ARQ (&lt;span class=&quot;tt&quot;&gt;llip-serial.scm&lt;/span&gt;)',['../index.html#llip-serial',1,'']]],
  ['array_90',['Typed numeric arrays (&lt;span class=&quot;tt&quot;&gt;array-*&lt;/span&gt;)',['../index.html#typed-vectors',1,'']]],
  ['array_20math_20linear_20algebra_91',['Array math (linear algebra)',['../index.html#ndarray',1,'']]],
  ['arrays_20array_92',['Typed numeric arrays (&lt;span class=&quot;tt&quot;&gt;array-*&lt;/span&gt;)',['../index.html#typed-vectors',1,'']]],
  ['as_20a_20master_93',['2. PROFIBUS DP as a Master',['../index.html#profibus-master',1,'']]],
  ['as_20a_20slave_94',['3. PROFIBUS DP as a Slave',['../index.html#profibus-slave',1,'']]],
  ['as_20linux_20and_20what_20is_20not_95',['What is the same as Linux, and what is not',['../index.html#autotoc_md6',1,'']]],
  ['as_20modbus_20controller_96',['2. LambLisp as Modbus Controller',['../index.html#modbus-controller',1,'']]],
  ['as_20modbus_20peripheral_97',['3. LambLisp as Modbus Peripheral',['../index.html#modbus-peripheral',1,'']]],
  ['as_20the_20universal_20glue_98',['7.2 LLIP as the Universal Glue',['../index.html#fwd-llip-glue',1,'']]],
  ['as_20virtual_20machines_99',['Control Applications as Virtual Machines.',['../index.html#autotoc_md37',1,'']]],
  ['ascii_20render_100',['5.2 Map Store and ASCII Render',['../index.html#fwd-cloud-mapstore',1,'']]],
  ['asked_20questions_101',['LambLisp Frequently Asked Questions',['../index.html#faq',1,'']]],
  ['ast_20→_20bytecode_20→_20native_20code_102',['Execution Tiers: AST → Bytecode → Native Code',['../index.html#arch-pipeline',1,'']]],
  ['asynchronous_20work_20—_20deferred_20task_20queue_103',['Asynchronous Work — Deferred Task Queue',['../index.html#autotoc_md45',1,'']]],
  ['at_20startup_104',['What Happens at Startup',['../index.html#startup',1,'']]],
  ['authority_105',['A string may contain NUL, and &lt;span class=&quot;tt&quot;&gt;string-length&lt;/span&gt; is the authority',['../index.html#autotoc_md147',1,'']]],
  ['autonomous_20fill_20behaviour_106',['3.3 Autonomous Fill Behaviour',['../index.html#fwd-autonomous',1,'']]],
  ['autonomous_20floor_20mapping_20with_20the_20freenove_204wd_20car_107',['Worked Example: Autonomous Floor Mapping with the Freenove 4WD Car',['../index.html#fwd-floor-mapping',1,'']]]
];
