var searchData=
[
  ['lambda_0',['lambda',['../index.html#autotoc_md54',1,'']]],
  ['lambda_20nlambda_20and_20macro_1',['lambda, nlambda, and macro',['../index.html#arch-lambda',1,'']]],
  ['lamblisp_2',['LambLisp',['../index.html#autotoc_md1',1,'Getting Started With Real-time &lt;em&gt;LambLisp&lt;/em&gt;'],['../index.html#autotoc_md179',1,'How fast is LambLisp?'],['../index.html#why-lamblisp',1,'Why &lt;em&gt;LambLisp&lt;/em&gt;?']]],
  ['lamblisp_20architecture_20internals_3',['LambLisp Architecture Internals',['../index.html#autotoc_md32',1,'']]],
  ['lamblisp_20as_20modbus_20controller_4',['2. LambLisp as Modbus Controller',['../index.html#modbus-controller',1,'']]],
  ['lamblisp_20as_20modbus_20peripheral_5',['3. LambLisp as Modbus Peripheral',['../index.html#modbus-peripheral',1,'']]],
  ['lamblisp_20block_20diagram_6',['LambLisp Block Diagram',['../index.html#autotoc_md38',1,'']]],
  ['lamblisp_20compatibility_20matrix_7',['LambLisp Compatibility Matrix',['../index.html#compat-matrix',1,'']]],
  ['lamblisp_20extensions_8',['LambLisp Extensions',['../index.html#autotoc_md74',1,'']]],
  ['lamblisp_20frequently_20asked_20questions_9',['LambLisp Frequently Asked Questions',['../index.html#faq',1,'']]],
  ['lamblisp_20in_20a_20container_10',['Running LambLisp in a Container',['../index.html#containers',1,'']]],
  ['lamblisp_20in_20combination_20with_20c_20c_20on_20micro_20controllers_11',['What are the advantages of &lt;em&gt;LambLisp&lt;/em&gt; in combination with C/C++ on micro-controllers?',['../index.html#autotoc_md197',1,'']]],
  ['lamblisp_20in_20your_20browser_12',['Quick Start: Try LambLisp in Your Browser',['../index.html#quick-start-browser',1,'']]],
  ['lamblisp_20instead_20of_20scheme_13',['Why is it called LambLisp instead of Scheme?',['../index.html#autotoc_md186',1,'']]],
  ['lamblisp_20interaction_20protocol_14',['LLIP — LambLisp Interaction Protocol',['../index.html#llip',1,'']]],
  ['lamblisp_20interoperate_20with_20c_20c_20code_15',['Does LambLisp interoperate with C/C++ code?',['../index.html#autotoc_md199',1,'']]],
  ['lamblisp_20modbus_20interface_16',['LambLisp Modbus Interface',['../index.html#modbus',1,'']]],
  ['lamblisp_20on_20linux_17',['Quick Start: Try LambLisp on Linux',['../index.html#quick-start',1,'']]],
  ['lamblisp_20on_20windows_18',['Quick Start: Try LambLisp on Windows',['../index.html#quick-start-windows',1,'']]],
  ['lamblisp_20open_20source_19',['Is LambLisp open source?',['../index.html#autotoc_md170',1,'']]],
  ['lamblisp_20profibus_20and_20profinet_20interface_20',['LambLisp PROFIBUS and PROFINET Interface',['../index.html#fieldbus',1,'']]],
  ['lamblisp_20right_20now_21',['How do I try LambLisp right now?',['../index.html#autotoc_md166',1,'']]],
  ['lamblisp_20run_20on_22',['What hardware does LambLisp run on?',['../index.html#autotoc_md168',1,'']]],
  ['lamblisp_20sit_20in_20the_20lisp_20landscape_23',['Where does LambLisp sit in the Lisp landscape?',['../index.html#autotoc_md190',1,'']]],
  ['lamblisp_20virtual_20machine_24',['LambLisp Virtual Machine',['../index.html#autotoc_md36',1,'']]],
  ['lamblisp_20without_20an_20rtos_25',['Can I use LambLisp without an RTOS?',['../index.html#autotoc_md201',1,'']]],
  ['landscape_26',['Where does LambLisp sit in the Lisp landscape?',['../index.html#autotoc_md190',1,'']]],
  ['language_27',['Core Language',['../index.html#autotoc_md132',1,'']]],
  ['language_28',['Try the language',['../index.html#autotoc_md7',1,'']]],
  ['language_20and_20conformance_29',['Language and Conformance',['../index.html#autotoc_md185',1,'']]],
  ['language_20extensions_30',['Language Extensions',['../index.html#language-extensions',1,'']]],
  ['language_20internals_20and_20c_20api_31',['Language Internals and C++ API',['../index.html#autotoc_md53',1,'']]],
  ['language_20specification_32',['Widely recognized &lt;em&gt;Scheme&lt;/em&gt; language specification',['../index.html#autotoc_md21',1,'']]],
  ['latency_20—_20no_20stop_20the_20world_20pauses_33',['GC Latency — No Stop-the-World Pauses',['../index.html#autotoc_md42',1,'']]],
  ['latency_20—_20sub_20microsecond_20isr_34',['Interrupt Latency — Sub-microsecond ISR',['../index.html#autotoc_md44',1,'']]],
  ['layer_35',['eye-cam.scm live-preview layer',['../index.html#autotoc_md102',1,'']]],
  ['layer_20llip_20http_20scm_36',['HTTP / LLM Layer (&lt;span class=&quot;tt&quot;&gt;llip-http.scm&lt;/span&gt;)',['../index.html#llip-http',1,'']]],
  ['lcd_20primitives_20c_37',['Camera / LCD primitives (C++)',['../index.html#autotoc_md101',1,'']]],
  ['lcd1602_20display_38',['LCD1602 Display',['../index.html#autotoc_md97',1,'']]],
  ['led_20ring_20service_20leds_20scm_39',['LED Ring Service (&lt;span class=&quot;tt&quot;&gt;Leds.scm&lt;/span&gt;)',['../index.html#autotoc_md105',1,'']]],
  ['led_20strip_20neopixel_40',['WS2812 Addressable LED Strip (NeoPixel)',['../index.html#autotoc_md99',1,'']]],
  ['leds_20scm_41',['LED Ring Service (&lt;span class=&quot;tt&quot;&gt;Leds.scm&lt;/span&gt;)',['../index.html#autotoc_md105',1,'']]],
  ['leds_20ws2812_20scm_42',['Addressable LEDs (&lt;span class=&quot;tt&quot;&gt;WS2812.scm&lt;/span&gt;)',['../index.html#autotoc_md104',1,'']]],
  ['legend_43',['Legend',['../index.html#autotoc_md127',1,'']]],
  ['length_20is_20the_20authority_44',['A string may contain NUL, and &lt;span class=&quot;tt&quot;&gt;string-length&lt;/span&gt; is the authority',['../index.html#autotoc_md147',1,'']]],
  ['lexical_20scoping_45',['Lexical scoping',['../index.html#autotoc_md27',1,'']]],
  ['libgpiod_46',['Real pins on a Jetson or Raspberry Pi (libgpiod)',['../index.html#llarduino-gpiod',1,'']]],
  ['libraries_47',['Bundled Scheme Libraries',['../index.html#scheme-libraries',1,'']]],
  ['libraries_48',['Reuse of existing C++/Arduino libraries',['../index.html#autotoc_md22',1,'']]],
  ['license_49',['License',['../index.html#license',1,'']]],
  ['lifecycle_50',['Connection Lifecycle',['../index.html#autotoc_md87',1,'']]],
  ['lifecycle_3a_20incremental_20hot_20reload_51',['Code Lifecycle: Incremental Hot-Reload',['../index.html#arch-lifecycle',1,'']]],
  ['light_20sensor_20lightsensor_20scm_52',['Light Sensor (&lt;span class=&quot;tt&quot;&gt;LightSensor.scm&lt;/span&gt;)',['../index.html#autotoc_md109',1,'']]],
  ['lightsensor_20scm_53',['Light Sensor (&lt;span class=&quot;tt&quot;&gt;LightSensor.scm&lt;/span&gt;)',['../index.html#autotoc_md109',1,'']]],
  ['lightweight_20object_20system_54',['Lightweight object system',['../index.html#autotoc_md62',1,'']]],
  ['like_20when_20you_20get_20it_20wrong_55',['What it looks like when you get it wrong',['../index.html#autotoc_md68',1,'']]],
  ['line_20client_3a_20tools_20llip_56',['Command-Line Client: &lt;span class=&quot;tt&quot;&gt;tools/llip&lt;/span&gt;',['../index.html#llip-cli',1,'']]],
  ['linear_20algebra_57',['Array math (linear algebra)',['../index.html#ndarray',1,'']]],
  ['linux_58',['Quick Start: Try LambLisp on Linux',['../index.html#quick-start',1,'']]],
  ['linux_20and_20what_20is_20not_59',['What is the same as Linux, and what is not',['../index.html#autotoc_md6',1,'']]],
  ['linux_20jetson_20builds_60',['Linux / Jetson Builds',['../index.html#autotoc_md14',1,'']]],
  ['linux_20x86_5f64_20and_20aarch64_61',['4.1 Linux (x86_64 and aarch64)',['../index.html#modbus-linux',1,'']]],
  ['lisp_62',['Why Lisp?',['../index.html#autotoc_md18',1,'']]],
  ['lisp_20and_20scheme_63',['Brief history of Lisp and Scheme',['../index.html#arch-history',1,'']]],
  ['lisp_20for_20microprocessors_64',['Real-time Lisp for Microprocessors',['../index.html',1,'']]],
  ['lisp_20in_20a_20nutshell_65',['&lt;em&gt;Lisp&lt;/em&gt; in a nutshell',['../index.html#autotoc_md17',1,'']]],
  ['lisp_20landscape_66',['Where does LambLisp sit in the Lisp landscape?',['../index.html#autotoc_md190',1,'']]],
  ['lisp_20primitives_67',['Open API for new &lt;em&gt;Lisp&lt;/em&gt; primitives',['../index.html#open-api',1,'']]],
  ['list_20structures_68',['Cell Memory Model and List Structures',['../index.html#autotoc_md41',1,'']]],
  ['lists_69',['Pairs and Lists',['../index.html#autotoc_md142',1,'']]],
  ['live_20preview_20layer_70',['eye-cam.scm live-preview layer',['../index.html#autotoc_md102',1,'']]],
  ['llip_71',['What is LLIP?',['../index.html#autotoc_md177',1,'']]],
  ['llip_72',['Command-Line Client: &lt;span class=&quot;tt&quot;&gt;tools/llip&lt;/span&gt;',['../index.html#llip-cli',1,'']]],
  ['llip_20—_20lamblisp_20interaction_20protocol_73',['LLIP — LambLisp Interaction Protocol',['../index.html#llip',1,'']]],
  ['llip_20as_20the_20universal_20glue_74',['7.2 LLIP as the Universal Glue',['../index.html#fwd-llip-glue',1,'']]],
  ['llip_20client_20scm_75',['Client API (&lt;span class=&quot;tt&quot;&gt;llip-client.scm&lt;/span&gt;)',['../index.html#autotoc_md90',1,'']]],
  ['llip_20http_20scm_76',['HTTP / LLM Layer (&lt;span class=&quot;tt&quot;&gt;llip-http.scm&lt;/span&gt;)',['../index.html#llip-http',1,'']]],
  ['llip_20serial_20scm_77',['Serial Transport and ARQ (&lt;span class=&quot;tt&quot;&gt;llip-serial.scm&lt;/span&gt;)',['../index.html#llip-serial',1,'']]],
  ['llip_20server_20scm_78',['Server (&lt;span class=&quot;tt&quot;&gt;llip-server.scm&lt;/span&gt;)',['../index.html#autotoc_md91',1,'']]],
  ['llip_20transport_20scm_79',['Device-Initiated Serving (&lt;span class=&quot;tt&quot;&gt;llip-transport.scm&lt;/span&gt;)',['../index.html#llip-device-serve',1,'']]],
  ['llm_20layer_20llip_20http_20scm_80',['HTTP / LLM Layer (&lt;span class=&quot;tt&quot;&gt;llip-http.scm&lt;/span&gt;)',['../index.html#llip-http',1,'']]],
  ['llvm_20for_20native_20code_20generation_81',['Why not use LLVM for native code generation?',['../index.html#autotoc_md194',1,'']]],
  ['loader_20wire_20contract_20nvs_82',['The loader wire contract (NVS)',['../index.html#autotoc_md79',1,'']]],
  ['looks_20like_20when_20you_20get_20it_20wrong_83',['What it looks like when you get it wrong',['../index.html#autotoc_md68',1,'']]],
  ['loop_84',['Loop',['../index.html#profibus-loop',1,'2.3 The Service Loop'],['../index.html#modbus-serve-loop',1,'3.4 The Serve Loop']]],
  ['loop_20time_20—_20bounded_20control_20cycle_85',['Loop Time — Bounded Control Cycle',['../index.html#autotoc_md43',1,'']]]
];
