var searchData=
[
  ['daemon_0',['5.1 Building the daemon',['../index.html#profinet-two-processes',1,'']]],
  ['data_1',['Structured Data',['../index.html#structured-data',1,'']]],
  ['data_20and_20scm_20are_20not_20the_20same_20thing_2',['&lt;span class=&quot;tt&quot;&gt;data/&lt;/span&gt; and &lt;span class=&quot;tt&quot;&gt;scm/&lt;/span&gt; are not the same thing',['../index.html#data-vs-scm',1,'']]],
  ['data_20marshaling_3',['Data Marshaling',['../index.html#autotoc_md73',1,'']]],
  ['data_20types_4',['Procedures are first-class data types',['../index.html#autotoc_md29',1,'']]],
  ['datagrams_5',['UDP Datagrams',['../index.html#udp',1,'']]],
  ['declaring_20slaves_6',['2.2 Declaring Slaves',['../index.html#profibus-add-slave',1,'']]],
  ['deferred_20task_20queue_7',['Asynchronous Work — Deferred Task Queue',['../index.html#autotoc_md45',1,'']]],
  ['demo_20sandbox_20scm_8',['Eval Sandbox (&lt;span class=&quot;tt&quot;&gt;demo-sandbox.scm&lt;/span&gt;)',['../index.html#autotoc_md123',1,'']]],
  ['demo_20supervisor_20scm_9',['Supervisory Control (&lt;span class=&quot;tt&quot;&gt;demo-supervisor.scm&lt;/span&gt;)',['../index.html#autotoc_md122',1,'']]],
  ['demo_20telemetry_20scm_10',['Telemetry &amp;amp; Floor Mapping (&lt;span class=&quot;tt&quot;&gt;demo-telemetry.scm&lt;/span&gt;)',['../index.html#autotoc_md124',1,'']]],
  ['demos_11',['Bundled Demos',['../index.html#demos',1,'']]],
  ['deploy_20to_20esp32_12',['Deploy to ESP32',['../index.html#deploy-esp32',1,'']]],
  ['derivatives_13',['Why not use embedded Python derivatives?',['../index.html#autotoc_md192',1,'']]],
  ['detailed_20compatibility_14',['Detailed Compatibility',['../index.html#autotoc_md131',1,'']]],
  ['details_15',['Hash table and hashing details',['../index.html#autotoc_md58',1,'']]],
  ['development_20tools_16',['Diagnostics and Development Tools',['../index.html#autotoc_md76',1,'']]],
  ['device_17',['PROFINET IO-Device',['../index.html#autotoc_md120',1,'']]],
  ['device_20initiated_20serving_20llip_20transport_20scm_18',['Device-Initiated Serving (&lt;span class=&quot;tt&quot;&gt;llip-transport.scm&lt;/span&gt;)',['../index.html#llip-device-serve',1,'']]],
  ['device_20model_19',['5.3 Device model',['../index.html#profinet-device-model',1,'']]],
  ['device_20patterns_20',['Device Patterns',['../index.html#autotoc_md70',1,'']]],
  ['diagnostics_20and_20development_20tools_21',['Diagnostics and Development Tools',['../index.html#autotoc_md76',1,'']]],
  ['diagnostics_20and_20global_20control_22',['2.5 Diagnostics and Global Control',['../index.html#profibus-diag',1,'']]],
  ['diagram_23',['LambLisp Block Diagram',['../index.html#autotoc_md38',1,'']]],
  ['dictionaries_24',['dictionaries',['../index.html#autotoc_md25',1,'First-class hierarchical dictionaries'],['../index.html#arch-hierdict',1,'Hierarchical dictionaries'],['../index.html#autotoc_md34',1,'Objects are wrappers around &lt;em&gt;hierarchical dictionaries&lt;/em&gt;']]],
  ['dictionary_25',['Execution environment is a &lt;em&gt;hierarchical dictionary&lt;/em&gt;',['../index.html#arch-envdict',1,'']]],
  ['dictionary_20environment_20operations_26',['Dictionary (Environment) Operations',['../index.html#autotoc_md75',1,'']]],
  ['dictionary_20type_27',['The &lt;em&gt;dictionary&lt;/em&gt; type',['../index.html#arch-dict',1,'']]],
  ['digital_20twin_28',['Digital Twin',['../index.html#autotoc_md95',1,'']]],
  ['digital_20twin_20sync_29',['4.4 Digital Twin Sync',['../index.html#fwd-jetson-twin',1,'']]],
  ['directory_30',['Running from any directory',['../index.html#autotoc_md5',1,'']]],
  ['display_31',['LCD1602 Display',['../index.html#autotoc_md97',1,'']]],
  ['display_20esp32_20s3_20eye_32',['Camera and On-Board Display (esp32-s3-eye)',['../index.html#camera',1,'']]],
  ['distributed_20environment_33',['Unified Distributed Environment',['../index.html#autotoc_md96',1,'']]],
  ['distribution_34',['Proprietary Distribution',['../index.html#autotoc_md72',1,'']]],
  ['dma_20memory_20and_20pre_20reserve_35',['Memory Tuning: Stack Size, DMA Memory, and Pre-Reserve',['../index.html#esp32-memory-tuning',1,'']]],
  ['do_20i_20try_20lamblisp_20right_20now_36',['How do I try LambLisp right now?',['../index.html#autotoc_md166',1,'']]],
  ['do_20i_20update_20code_20without_20reflashing_37',['How do I update code without reflashing?',['../index.html#autotoc_md172',1,'']]],
  ['documentation_20is_20already_20inside_38',['The documentation is already inside',['../index.html#autotoc_md9',1,'']]],
  ['does_20lamblisp_20interoperate_20with_20c_20c_20code_39',['Does LambLisp interoperate with C/C++ code?',['../index.html#autotoc_md199',1,'']]],
  ['does_20lamblisp_20run_20on_40',['What hardware does LambLisp run on?',['../index.html#autotoc_md168',1,'']]],
  ['does_20lamblisp_20sit_20in_20the_20lisp_20landscape_41',['Where does LambLisp sit in the Lisp landscape?',['../index.html#autotoc_md190',1,'']]],
  ['does_20not_20run_20on_20embedded_20hardware_42',['Why the compiled tier does not run on embedded hardware',['../index.html#autotoc_md35',1,'']]],
  ['does_20not_20work_43',['When it does not work',['../index.html#package-troubleshooting',1,'']]],
  ['does_20the_20same_20scheme_20code_20run_20on_20all_20platforms_44',['Does the same Scheme code run on all platforms?',['../index.html#autotoc_md183',1,'']]],
  ['dp_20as_20a_20master_45',['2. PROFIBUS DP as a Master',['../index.html#profibus-master',1,'']]],
  ['dp_20as_20a_20slave_46',['3. PROFIBUS DP as a Slave',['../index.html#profibus-slave',1,'']]],
  ['dp_20master_47',['PROFIBUS DP master',['../index.html#autotoc_md118',1,'']]],
  ['dp_20slave_48',['PROFIBUS DP slave',['../index.html#autotoc_md119',1,'']]],
  ['drives_20a_20pin_49',['Where these run, and what actually drives a pin',['../index.html#llarduino-backends',1,'']]]
];
