var searchData=
[
  ['package_0',['package',['../index.html#package-contents',1,'What is in the package'],['../index.html#whats-in-the-package',1,'What&apos;s in the package?']]],
  ['package_20you_20received_1',['Quick Start: The Package You Received',['../index.html#quick-start-package',1,'']]],
  ['pairs_20and_20lists_2',['Pairs and Lists',['../index.html#autotoc_md142',1,'']]],
  ['parameters_3',['6.4 Tuning Parameters',['../index.html#fwd-run-tuning',1,'']]],
  ['patterns_4',['Device Patterns',['../index.html#autotoc_md70',1,'']]],
  ['pauses_5',['GC Latency — No Stop-the-World Pauses',['../index.html#autotoc_md42',1,'']]],
  ['pca9685_20pwm_20controller_6',['PCA9685 PWM Controller',['../index.html#autotoc_md98',1,'']]],
  ['pca9685_20scm_7',['Servos and Motors (&lt;span class=&quot;tt&quot;&gt;PCA9685.scm&lt;/span&gt;)',['../index.html#autotoc_md103',1,'']]],
  ['pcf8574_20scm_8',['I2C GPIO Expander (&lt;span class=&quot;tt&quot;&gt;PCF8574.scm&lt;/span&gt;)',['../index.html#autotoc_md108',1,'']]],
  ['peripheral_9',['Peripheral',['../index.html#modbus-peripheral',1,'3. LambLisp as Modbus Peripheral'],['../index.html#modbus-peripheral-open',1,'3.1 Opening a Peripheral']]],
  ['peripheral_20functions_10',['Peripheral Functions',['../index.html#autotoc_md117',1,'']]],
  ['peripheral_20summary_11',['Freenove 4WD Car Kit — Peripheral Summary',['../index.html#autotoc_md100',1,'']]],
  ['personality_20personality_20scm_12',['Personality (&lt;span class=&quot;tt&quot;&gt;Personality.scm&lt;/span&gt;)',['../index.html#autotoc_md126',1,'']]],
  ['personality_20scm_13',['Personality (&lt;span class=&quot;tt&quot;&gt;Personality.scm&lt;/span&gt;)',['../index.html#autotoc_md126',1,'']]],
  ['pi_20libgpiod_14',['Real pins on a Jetson or Raspberry Pi (libgpiod)',['../index.html#llarduino-gpiod',1,'']]],
  ['pin_15',['Where these run, and what actually drives a pin',['../index.html#llarduino-backends',1,'']]],
  ['pins_20on_20a_20jetson_20or_20raspberry_20pi_20libgpiod_16',['Real pins on a Jetson or Raspberry Pi (libgpiod)',['../index.html#llarduino-gpiod',1,'']]],
  ['plan_17',['4.2 Requesting a Coverage Plan',['../index.html#fwd-jetson-plan',1,'']]],
  ['planner_18',['5.1 Boustrophedon Coverage Planner',['../index.html#fwd-cloud-planner',1,'']]],
  ['platform_19',['Multi-platform',['../index.html#autotoc_md20',1,'']]],
  ['platform_20a_20guard_20that_20means_20has_20a_20socket_20must_20now_20say_20so_20',['platform. A guard that means &quot;has a socket&quot; must now SAY so.',['../ll__platform__generic_8h.html#autotoc_md206',1,'']]],
  ['platform_20notes_21',['4. Platform Notes',['../index.html#modbus-platform',1,'']]],
  ['platform_20support_22',['Multi-Platform Support',['../index.html#arch-multiplatform',1,'']]],
  ['platforms_23',['Does the same Scheme code run on all platforms?',['../index.html#autotoc_md183',1,'']]],
  ['platforms_20and_20boards_24',['Supported Platforms and Boards',['../index.html#supported-platforms',1,'']]],
  ['point_20softap_25',['WiFi Access Point (softAP)',['../index.html#wifi-softap',1,'']]],
  ['poll_20model_26',['2.2 The Non-Blocking Request/Poll Model',['../index.html#modbus-poll-model',1,'']]],
  ['ports_27',['Ports',['../index.html#autotoc_md157',1,'']]],
  ['pre_20reserve_28',['Memory Tuning: Stack Size, DMA Memory, and Pre-Reserve',['../index.html#esp32-memory-tuning',1,'']]],
  ['precision_20integers_20bignums_29',['Arbitrary-Precision Integers (Bignums)',['../index.html#bignum',1,'']]],
  ['prerequisites_30',['Prerequisites',['../index.html#prerequisites',1,'']]],
  ['preview_20layer_31',['eye-cam.scm live-preview layer',['../index.html#autotoc_md102',1,'']]],
  ['primitives_32',['3.2 Motion Primitives',['../index.html#fwd-motion',1,'']]],
  ['primitives_33',['Open API for new &lt;em&gt;Lisp&lt;/em&gt; primitives',['../index.html#open-api',1,'']]],
  ['primitives_20c_34',['Camera / LCD primitives (C++)',['../index.html#autotoc_md101',1,'']]],
  ['procedures_35',['Procedures',['../index.html#mop3-gc-rules',1,'Garbage Collection Rules for C++ Procedures'],['../index.html#arch-mop3',1,'Stateless Procedures']]],
  ['procedures_20are_20first_20class_20data_20types_36',['Procedures are first-class data types',['../index.html#autotoc_md29',1,'']]],
  ['procedures_20that_20can_20throw_37',['Procedures that can throw',['../index.html#autotoc_md67',1,'']]],
  ['profibus_20and_20profinet_20interface_38',['LambLisp PROFIBUS and PROFINET Interface',['../index.html#fieldbus',1,'']]],
  ['profibus_20dp_20as_20a_20master_39',['2. PROFIBUS DP as a Master',['../index.html#profibus-master',1,'']]],
  ['profibus_20dp_20as_20a_20slave_40',['3. PROFIBUS DP as a Slave',['../index.html#profibus-slave',1,'']]],
  ['profibus_20dp_20master_41',['PROFIBUS DP master',['../index.html#autotoc_md118',1,'']]],
  ['profibus_20dp_20slave_42',['PROFIBUS DP slave',['../index.html#autotoc_md119',1,'']]],
  ['profinet_43',['5. PROFINET',['../index.html#profinet',1,'']]],
  ['profinet_20interface_44',['LambLisp PROFIBUS and PROFINET Interface',['../index.html#fieldbus',1,'']]],
  ['profinet_20io_20device_45',['PROFINET IO-Device',['../index.html#autotoc_md120',1,'']]],
  ['proprietary_20distribution_46',['Proprietary Distribution',['../index.html#autotoc_md72',1,'']]],
  ['protecting_47',['What needs protecting',['../index.html#autotoc_md65',1,'']]],
  ['protocol_48',['LLIP — LambLisp Interaction Protocol',['../index.html#llip',1,'']]],
  ['pwm_20controller_49',['PCA9685 PWM Controller',['../index.html#autotoc_md98',1,'']]],
  ['python_20derivatives_50',['Why not use embedded Python derivatives?',['../index.html#autotoc_md192',1,'']]]
];
