var searchData=
[
  ['b_20—_20speed_0',['Group B — Speed',['../index.html#autotoc_md49',1,'']]],
  ['background_1',['Background',['../index.html#autotoc_md33',1,'']]],
  ['baud_20ceiling_20and_20why_20it_20exists_2',['The baud ceiling, and why it exists',['../index.html#profibus-baud-ceiling',1,'']]],
  ['bee_20strategy_20module_3',['3.5 Bee Strategy Module',['../index.html#fwd-bee-onboard',1,'']]],
  ['bee_20strategy_20server_4',['5.3 Bee Strategy Server',['../index.html#fwd-cloud-bee',1,'']]],
  ['behaviors_3a_20cooperative_20scheduling_5',['Behaviors: Cooperative Scheduling',['../index.html#behaviors',1,'']]],
  ['behaviour_6',['3.3 Autonomous Fill Behaviour',['../index.html#fwd-autonomous',1,'']]],
  ['bignums_7',['Arbitrary-Precision Integers (Bignums)',['../index.html#bignum',1,'']]],
  ['binary_20framing_20struct_8',['Binary framing (struct)',['../index.html#struct',1,'']]],
  ['block_20diagram_9',['LambLisp Block Diagram',['../index.html#autotoc_md38',1,'']]],
  ['blocking_20request_20poll_20model_10',['2.2 The Non-Blocking Request/Poll Model',['../index.html#modbus-poll-model',1,'']]],
  ['board_11',['board',['../index.html#package-flash',1,'Flash an embedded board'],['../index.html#package-connect',1,'Talk to the board']]],
  ['board_20car_20code_12',['3. On-Board Car Code',['../index.html#fwd-onboard',1,'']]],
  ['board_20display_20esp32_20s3_20eye_13',['Camera and On-Board Display (esp32-s3-eye)',['../index.html#camera',1,'']]],
  ['boards_14',['Supported Platforms and Boards',['../index.html#supported-platforms',1,'']]],
  ['boot_20confirm_20rollback_20model_15',['The boot-confirm / rollback model',['../index.html#autotoc_md80',1,'']]],
  ['bounded_20control_20cycle_16',['Loop Time — Bounded Control Cycle',['../index.html#autotoc_md43',1,'']]],
  ['boustrophedon_20coverage_20planner_17',['5.1 Boustrophedon Coverage Planner',['../index.html#fwd-cloud-planner',1,'']]],
  ['brief_20history_20of_20lisp_20and_20scheme_18',['Brief history of Lisp and Scheme',['../index.html#arch-history',1,'']]],
  ['browser_19',['Quick Start: Try LambLisp in Your Browser',['../index.html#quick-start-browser',1,'']]],
  ['build_20',['Build',['../index.html#package-build',1,'']]],
  ['build_20and_20flash_21',['Build and Flash',['../index.html#autotoc_md15',1,'']]],
  ['build_20flag_20summary_22',['4.3 Build Flag Summary',['../index.html#modbus-build-flags',1,'']]],
  ['build_20flags_23',['7. Build Flags',['../index.html#fieldbus-build-flags',1,'']]],
  ['building_20the_20daemon_24',['5.1 Building the daemon',['../index.html#profinet-two-processes',1,'']]],
  ['builds_25',['Linux / Jetson Builds',['../index.html#autotoc_md14',1,'']]],
  ['bundled_20demos_26',['Bundled Demos',['../index.html#demos',1,'']]],
  ['bundled_20scheme_20libraries_27',['Bundled Scheme Libraries',['../index.html#scheme-libraries',1,'']]],
  ['bus_28',['Bus',['../index.html#profibus-open',1,'2.1 Opening the Bus'],['../index.html#onewire',1,'OneWire (1-Wire Bus)'],['../index.html#spi',1,'SPI Bus']]],
  ['bus_20utilities_20i2c_20scm_29',['I2C Bus Utilities (&lt;span class=&quot;tt&quot;&gt;I2C.scm&lt;/span&gt;)',['../index.html#autotoc_md110',1,'']]],
  ['buzzer_20buzzer_20scm_30',['Buzzer (&lt;span class=&quot;tt&quot;&gt;Buzzer.scm&lt;/span&gt;)',['../index.html#autotoc_md106',1,'']]],
  ['buzzer_20scm_31',['Buzzer (&lt;span class=&quot;tt&quot;&gt;Buzzer.scm&lt;/span&gt;)',['../index.html#autotoc_md106',1,'']]],
  ['bytecode_20→_20native_20code_32',['Execution Tiers: AST → Bytecode → Native Code',['../index.html#arch-pipeline',1,'']]],
  ['bytecode_20ncg_20compilation_33',['What is bytecode / NCG compilation?',['../index.html#autotoc_md181',1,'']]],
  ['bytecode_20virtual_20machine_34',['Bytecode Virtual Machine',['../index.html#arch-bc',1,'']]],
  ['bytevectors_35',['Bytevectors',['../index.html#autotoc_md151',1,'']]]
];
