var searchData=
[
  ['raspberry_20pi_20libgpiod_0',['Real pins on a Jetson or Raspberry Pi (libgpiod)',['../index.html#llarduino-gpiod',1,'']]],
  ['reach_1',['Reach',['../index.html#autotoc_md46',1,'Group A — Reach'],['../index.html#autotoc_md47',1,'Network Reach']]],
  ['real_20pins_20on_20a_20jetson_20or_20raspberry_20pi_20libgpiod_2',['Real pins on a Jetson or Raspberry Pi (libgpiod)',['../index.html#llarduino-gpiod',1,'']]],
  ['real_20time_20control_3',['Real-time control',['../index.html#autotoc_md19',1,'']]],
  ['real_20time_20control_20system_4',['What is a real-time control system?',['../index.html#autotoc_md175',1,'']]],
  ['real_20time_20garbage_20collection_5',['Adaptive real-time garbage collection',['../index.html#autotoc_md23',1,'']]],
  ['real_20time_20guarantees_6',['Real-time Guarantees',['../index.html#arch-realtime',1,'']]],
  ['real_20time_20lamblisp_7',['Getting Started With Real-time &lt;em&gt;LambLisp&lt;/em&gt;',['../index.html#autotoc_md1',1,'']]],
  ['real_20time_20lisp_20for_20microprocessors_8',['Real-time Lisp for Microprocessors',['../index.html',1,'']]],
  ['reboot_9',['Hot-Reload Without Reboot',['../index.html#llip-hotreload',1,'']]],
  ['reboot_10',['Incremental over-the-air updates without reboot',['../index.html#autotoc_md24',1,'']]],
  ['received_11',['Quick Start: The Package You Received',['../index.html#quick-start-package',1,'']]],
  ['recognized_20scheme_20language_20specification_12',['Widely recognized &lt;em&gt;Scheme&lt;/em&gt; language specification',['../index.html#autotoc_md21',1,'']]],
  ['recursion_20and_20tail_20calls_13',['Tail recursion and tail-calls',['../index.html#autotoc_md28',1,'']]],
  ['reference_14',['Reference',['../index.html#modbus-quickref',1,'5. Quick Reference'],['../index.html#fieldbus-quickref',1,'8. Quick Reference']]],
  ['reflashing_15',['How do I update code without reflashing?',['../index.html#autotoc_md172',1,'']]],
  ['register_20accessors_16',['3.3 Register Accessors',['../index.html#modbus-register-accessors',1,'']]],
  ['register_20tables_17',['3.2 The Four Register Tables',['../index.html#modbus-register-tables',1,'']]],
  ['release_20is_20in_20the_20image_18',['Which release is in the image',['../index.html#autotoc_md10',1,'']]],
  ['reload_19',['Code Lifecycle: Incremental Hot-Reload',['../index.html#arch-lifecycle',1,'']]],
  ['reload_20without_20reboot_20',['Hot-Reload Without Reboot',['../index.html#llip-hotreload',1,'']]],
  ['render_21',['5.2 Map Store and ASCII Render',['../index.html#fwd-cloud-mapstore',1,'']]],
  ['repl_22',['REPL',['../index.html#autotoc_md16',1,'Connect to the REPL'],['../index.html#autotoc_md12',1,'Using the REPL']]],
  ['request_23',['Controller Function Codes (symbols for &lt;span class=&quot;tt&quot;&gt;modbus-request&lt;/span&gt;)',['../index.html#autotoc_md116',1,'']]],
  ['request_20poll_20model_24',['2.2 The Non-Blocking Request/Poll Model',['../index.html#modbus-poll-model',1,'']]],
  ['requesting_20a_20coverage_20plan_25',['4.2 Requesting a Coverage Plan',['../index.html#fwd-jetson-plan',1,'']]],
  ['reserve_26',['Memory Tuning: Stack Size, DMA Memory, and Pre-Reserve',['../index.html#esp32-memory-tuning',1,'']]],
  ['reuse_20of_20existing_20c_20arduino_20libraries_27',['Reuse of existing C++/Arduino libraries',['../index.html#autotoc_md22',1,'']]],
  ['right_20now_28',['How do I try LambLisp right now?',['../index.html#autotoc_md166',1,'']]],
  ['ring_20service_20leds_20scm_29',['LED Ring Service (&lt;span class=&quot;tt&quot;&gt;Leds.scm&lt;/span&gt;)',['../index.html#autotoc_md105',1,'']]],
  ['robot_20stack_30',['AI Orchestration and the Robot Stack',['../index.html#llip-robot',1,'']]],
  ['role_20in_20the_20supervisory_20architecture_31',['Role in the Supervisory Architecture',['../index.html#autotoc_md93',1,'']]],
  ['rollback_20model_32',['The boot-confirm / rollback model',['../index.html#autotoc_md80',1,'']]],
  ['rooted_20for_20you_33',['What is already rooted for you',['../index.html#autotoc_md64',1,'']]],
  ['rs_20485_20wiring_34',['4. RS-485 Wiring',['../index.html#profibus-wiring',1,'']]],
  ['rtos_35',['Can I use LambLisp without an RTOS?',['../index.html#autotoc_md201',1,'']]],
  ['rules_20for_20c_20procedures_36',['Garbage Collection Rules for C++ Procedures',['../index.html#mop3-gc-rules',1,'']]],
  ['rules_20the_20macro_20cannot_20enforce_37',['Two rules the macro cannot enforce',['../index.html#autotoc_md66',1,'']]],
  ['run_20and_20what_20actually_20drives_20a_20pin_38',['Where these run, and what actually drives a pin',['../index.html#llarduino-backends',1,'']]],
  ['run_20it_39',['Run it',['../index.html#autotoc_md4',1,'']]],
  ['run_20on_40',['What hardware does LambLisp run on?',['../index.html#autotoc_md168',1,'']]],
  ['run_20on_20all_20platforms_41',['Does the same Scheme code run on all platforms?',['../index.html#autotoc_md183',1,'']]],
  ['run_20on_20embedded_20hardware_42',['Why the compiled tier does not run on embedded hardware',['../index.html#autotoc_md35',1,'']]],
  ['run_20the_20supervisor_20on_20the_20jetson_43',['6.3 Run the Supervisor on the Jetson',['../index.html#fwd-run-jetson',1,'']]],
  ['running_20from_20any_20directory_44',['Running from any directory',['../index.html#autotoc_md5',1,'']]],
  ['running_20lamblisp_20in_20a_20container_45',['Running LambLisp in a Container',['../index.html#containers',1,'']]],
  ['running_20the_20example_46',['6. Running the Example',['../index.html#fwd-run',1,'']]],
  ['runtime_20and_20gc_20tuning_47',['Runtime and GC Tuning',['../index.html#gc-tuning',1,'']]],
  ['runtime_20collaboration_20with_20c_20code_48',['Runtime collaboration with C++ code',['../index.html#autotoc_md30',1,'']]]
];
